// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUnSF2roaNfXdmT4Ch2X451yw6pKq1yiA',
    appId: '1:204208997305:web:a2058ac80a1a96d9c76c68',
    messagingSenderId: '204208997305',
    projectId: 'updown-7db17',
    authDomain: 'updown-7db17.firebaseapp.com',
    storageBucket: 'updown-7db17.appspot.com',
    measurementId: 'G-HQZ7642ZRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxyUB2a_TTRf6VO5vnHP_sTmxrGyBjlR4',
    appId: '1:204208997305:android:2e27c8516340640fc76c68',
    messagingSenderId: '204208997305',
    projectId: 'updown-7db17',
    storageBucket: 'updown-7db17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASyWHTy5yKEPkTGmCHouuoi_m6mdottJI',
    appId: '1:204208997305:ios:d45f83ff64bbe026c76c68',
    messagingSenderId: '204208997305',
    projectId: 'updown-7db17',
    storageBucket: 'updown-7db17.appspot.com',
    iosClientId: '204208997305-ts5amhem7g4lleemhs620adpn8a2gfrd.apps.googleusercontent.com',
    iosBundleId: 'com.example.updown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASyWHTy5yKEPkTGmCHouuoi_m6mdottJI',
    appId: '1:204208997305:ios:d45f83ff64bbe026c76c68',
    messagingSenderId: '204208997305',
    projectId: 'updown-7db17',
    storageBucket: 'updown-7db17.appspot.com',
    iosClientId: '204208997305-ts5amhem7g4lleemhs620adpn8a2gfrd.apps.googleusercontent.com',
    iosBundleId: 'com.example.updown',
  );
}
